MODEL:
  TYPE: 'hrnet'
  STAGE1:
    NUM_MODULES: 1
    NUM_CHANNELS: [64]
    NUM_BLOCKS: [4]
    BLOCK: 'bottleneck'
    UPSAMPLE: 'transpose'
  STAGE2:
    NUM_MODULES: 1
    NUM_CHANNELS: [32, 64]
    NUM_BLOCKS: [4, 4]
    BLOCK: 'basic'
    UPSAMPLE: 'transpose'
  STAGE3:
    NUM_MODULES: 4
    NUM_CHANNELS: [32, 64, 128]
    NUM_BLOCKS: [4, 4, 4]
    BLOCK: 'basic'
    UPSAMPLE: 'transpose'
  STAGE4:
    NUM_MODULES: 3
    NUM_CHANNELS: [32, 64, 128, 256]
    NUM_BLOCKS: [4, 4, 4, 4]
    BLOCK: 'basic'
    UPSAMPLE: 'transpose'

TRAIN:
  BATCH_SIZE: 256
  EPOCHS: 200
  WARMUP_EPOCHS: 5
  LR_SCHEDULE: 'warmup_cosine_decay'
  SAVE_META: true

VAL:
  BATCH_SIZE: 256
  DROP_REMAINDER: True
  DET: True

DATASET:
  TFRECORDS: 'gs://bucket/TF2-SimpleHumanPose/tfrecords'
  ANNOT: '/home/user/coco/annotations/person_keypoints_val2017.json'
  CACHE: true
  BFLOAT16: true


